### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by jacobvorr** [NormanhurstRoverCrew/mmt-web#2]
- [x] Setup Docker compose
- [x] Setup and Install Linting for all languages
- [x] Setup and Install test platform for unittesting including coverage reporting
- [x] Setup build file for npm including automatic package installer
- [x] Investigate using make
- [x] Set up CircleCI

**Comment by grantperry** [comment]
Regarding 'Investigate using make'
Considering all building should be done by docker(Dockerfile) and all runtime should be managed by docker-compose I dont think make is a nescessary tool.

In saying that, make could be used to run any scripts for environment set up(eg database setup) but this can be thought about at a later date.

Thoughts @jacobvorr?

**Comment by grantperry** [comment]
Closing as all points have been discuessed and/or implemented
only point not implemented is 'Investigate using make' due to docker taking up the job that make normally does
